loglevel: debug
logfile: test.log
pfctl:
  enable: false
  path: "/usr/sbin/pfctl"
  suffix: "_clients"

mysql:
  host: ""
# Refer to the DSN connection string
# https://github.com/go-sql-driver/mysql#dsn-data-source-name
# host: "tcp(127.0.0.1:3306)"
# properties: "param1=value1&...&paramN=valueN"
  username: root
  password: ""
  database: echoCTF

memcache:
  host: "127.0.0.1:11211"
